pipelines:
  hop:
    group: hop
    materials:
      repo:
        git: https://github.com/dudadornelles/hop.git
    stages:
      - build:
          tasks:
            - script: virtualenv ~/.hopvenv -p python3.5 && source ~/.hopvenv/bin/activate && make test
